### ISSUE TITLE
[video_player_web] Videos arn't visible in Safari/Chrome on iOS

### ISSUE THREAD

**Issue by mrinaljain** [GeekyAnts/flick-video-player#99]
flick_video_player can play in Mac safari normally by platform web, but when I play in phone safari, it doesn't work, only audio can be heard but there is no video visible.

following is my sample code for safari/ios, I have turned autoplay off and volume to 0 because safari does not support autoplay  of unmuted video

```
flickManager = FlickManager(
          videoPlayerController: VideoPlayerController.network(
              "https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4")
          autoPlay: false);
      flickManager?.flickControlManager?.mute();
      flickManager?.flickControlManager?.setVolume(0);
```

an  issue regarding the video_player_web was resolved   here   https://github.com/flutter/flutter/issues/47030
but the problem still persists in the flick video player.

**Comment by geekruchika** [comment]
Thanks for pointing out. Resolved in 0.4.0-dev.2.

**Comment by NehaKushwah993** [comment]
Seeing same issue, for m3u8 videos in Safari of iPhone.

**Comment by mrinaljain** [comment]
@NehaKushwah993 
Try using video_player_web_hls plugin.
It will serve your purpose.

Thanks

**Comment by NehaKushwahIgnite** [comment]
Hi, Thanks for the reply.
video_player_web_hls: ^0.1.11+2  is already used, but still getting issue only in iOS Safari, only audio no video.

**Comment by ashishignitesol** [comment]
mp4 plays fine but not m3u8

**Comment by NehaKushwahIgnite** [comment]
Also its working fine with normal VideoPlayer (flutter), but not with Flicker.

**Comment by Joseph-Nathan** [comment]
i have the same problem ,( Web on Chrome on Mac )
and when i change the url_source it work 2 audio in same moment and previous video ,
and when i popup the 2 audio still work ( not dispose )

**Comment by mrinaljain** [comment]
The issue still persists in the latest version of the player
